version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        tty: true
        ports:
            - 8000:80
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        networks:
            - app-network

    app_db:
        image: mysql:5.7.22
        volumes:
            - ./db:/var/lib/mysql
        container_name: app_db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: app_db
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
